version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.1"
    working_directory: /Users/slashmo/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: unit
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: pre-start simulator
          command: xcrun instruments -w "iPhone XS (12.1) [" || true
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
